### ISSUE TITLE
How to use moment inside template?

### ISSUE THREAD

**Issue by Abhivendra** [saaadel/angular-moment-timezone#1]
I want to use moment.fromNow() in the angular material table in my template. How to do it?

**Comment by saaadel** [comment]
This repo is for timezone shifts only. I think you need ask it in https://github.com/urish/angular2-moment - There's everything about moment namespace.
Anyway, I see there are no solution for you right now. You can write your own pipe for it by yourself.

Something like following code:
```javascript
import {Pipe, PipeTransform} from "@angular/core";
import * as moment from "moment-timezone";

@Pipe({
  name: 'amFromNow'
})
export class FromNowPipe implements PipeTransform {

  transform(value: moment.MomentInput, withoutSuffix: boolean = false): string {
    return moment(value).fromNow(!!withoutSuffix);
  }
}
```

How to use:
```html
<span>{{ momentValue | amFromNow }} </span> <!-- With 'ago' suffix -->
<span>{{ momentValue | amFromNow:true }} </span> <!-- Without it -->
```
