### ISSUE TITLE
Doesn't work with Angular 5.0

### ISSUE THREAD

**Issue by nashmaniac** [saaadel/angular-moment-timezone#2]
When I tried to build after upgrading from angular 4.4.6 to angular 5.0 I get this error...
`
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /Users/shetu/workplace/1/angular-demo/node_modules/angular-moment-timezone/node_modules/@angular/core/core.d.ts, resolving symbol MomentTimezoneModule in /Users/shetu/workplace/1/angular-demo/node_modules/angular-moment-timezone/moment-timezone.module.d.ts, resolving symbol MomentTimezoneModule in /Users/shetu/workplace/1/angular-demo/node_modules/angular-moment-timezone/moment-timezone.module.d.ts
`

Can you please let me know what is wrong here.?

**Comment by saaadel** [comment]
try with angular-moment-timezone@1.7.0
and give me know

**Comment by orwtech** [comment]
This is still an issue in 5.0.4 importing MomentTimezoneModule in AppModule

**Comment by gubagu** [comment]
Same here

**Comment by nashmaniac** [comment]
I have written a small custom timezone conversion code. using that.

**Comment by saaadel** [comment]
sorry guys, I was too busy last days. I can fix and test it at this weekend

**Comment by nassan** [comment]
Hey. Having an issue as well. Any timeframe on the fix? Any idea what the problem is, maybe I could fix it?

**Comment by saaadel** [comment]
Use tag published-1.7.1 or npm install angular-moment-timezone@1.7.1
It works with angular 5.1.0 (tested)

**Comment by saaadel** [comment]
sorry for delay

**Comment by saaadel** [comment]
also, jsdoc added

**Comment by Rahul-Bhaskaran** [comment]
Not working with angular 7.0.0

**Comment by utiq** [comment]
@Rahul-Bhaskaran how did you solve it? I have the same problem
